//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Mauricio/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""608ace37-73d4-47b6-94ce-7222d134184b"",
            ""actions"": [
                {
                    ""name"": ""FirstContact"",
                    ""type"": ""PassThrough"",
                    ""id"": ""101a3ddd-9cad-417c-98a0-3739c4112795"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""56ceb425-10b1-401a-9b55-8566386d8b75"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""050a9a80-1a4d-4909-a34e-d0b2fbf149a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold"",
                    ""type"": ""Button"",
                    ""id"": ""6ecdf1cb-3445-4f63-8a06-ec6574d2d00b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.15)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ac9f1a64-6cdc-4d36-be32-73fa41be841e"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""833a42ca-f022-4561-b83d-ee6d8e7aefc7"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2872116c-8d38-40a7-9f84-511f6d5fe62a"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0d11d30-3b49-48ea-87ef-4f979d82c413"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""771cf746-05ef-44db-a5b7-d11940ad2d5b"",
            ""actions"": [
                {
                    ""name"": ""Debug"",
                    ""type"": ""Button"",
                    ""id"": ""fa6e3427-2af7-46f4-aed2-036f6e7acdfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b270886-09b2-480a-b9b9-52672558ee26"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_FirstContact = m_Touch.FindAction("FirstContact", throwIfNotFound: true);
        m_Touch_FirstPosition = m_Touch.FindAction("FirstPosition", throwIfNotFound: true);
        m_Touch_Tap = m_Touch.FindAction("Tap", throwIfNotFound: true);
        m_Touch_Hold = m_Touch.FindAction("Hold", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_Debug = m_Debug.FindAction("Debug", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_FirstContact;
    private readonly InputAction m_Touch_FirstPosition;
    private readonly InputAction m_Touch_Tap;
    private readonly InputAction m_Touch_Hold;
    public struct TouchActions
    {
        private @PlayerController m_Wrapper;
        public TouchActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstContact => m_Wrapper.m_Touch_FirstContact;
        public InputAction @FirstPosition => m_Wrapper.m_Touch_FirstPosition;
        public InputAction @Tap => m_Wrapper.m_Touch_Tap;
        public InputAction @Hold => m_Wrapper.m_Touch_Hold;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @FirstContact.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstContact;
                @FirstContact.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstContact;
                @FirstContact.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstContact;
                @FirstPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstPosition;
                @FirstPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstPosition;
                @FirstPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstPosition;
                @Tap.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTap;
                @Tap.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTap;
                @Tap.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTap;
                @Hold.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnHold;
                @Hold.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnHold;
                @Hold.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnHold;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FirstContact.started += instance.OnFirstContact;
                @FirstContact.performed += instance.OnFirstContact;
                @FirstContact.canceled += instance.OnFirstContact;
                @FirstPosition.started += instance.OnFirstPosition;
                @FirstPosition.performed += instance.OnFirstPosition;
                @FirstPosition.canceled += instance.OnFirstPosition;
                @Tap.started += instance.OnTap;
                @Tap.performed += instance.OnTap;
                @Tap.canceled += instance.OnTap;
                @Hold.started += instance.OnHold;
                @Hold.performed += instance.OnHold;
                @Hold.canceled += instance.OnHold;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_Debug;
    public struct DebugActions
    {
        private @PlayerController m_Wrapper;
        public DebugActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Debug => m_Wrapper.m_Debug_Debug;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @Debug.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug;
                @Debug.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug;
                @Debug.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Debug.started += instance.OnDebug;
                @Debug.performed += instance.OnDebug;
                @Debug.canceled += instance.OnDebug;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    public interface ITouchActions
    {
        void OnFirstContact(InputAction.CallbackContext context);
        void OnFirstPosition(InputAction.CallbackContext context);
        void OnTap(InputAction.CallbackContext context);
        void OnHold(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnDebug(InputAction.CallbackContext context);
    }
}
