//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""608ace37-73d4-47b6-94ce-7222d134184b"",
            ""actions"": [
                {
                    ""name"": ""FirstContact"",
                    ""type"": ""PassThrough"",
                    ""id"": ""101a3ddd-9cad-417c-98a0-3739c4112795"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""56ceb425-10b1-401a-9b55-8566386d8b75"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ac9f1a64-6cdc-4d36-be32-73fa41be841e"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""833a42ca-f022-4561-b83d-ee6d8e7aefc7"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_FirstContact = m_Touch.FindAction("FirstContact", throwIfNotFound: true);
        m_Touch_FirstPosition = m_Touch.FindAction("FirstPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_FirstContact;
    private readonly InputAction m_Touch_FirstPosition;
    public struct TouchActions
    {
        private @PlayerController m_Wrapper;
        public TouchActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstContact => m_Wrapper.m_Touch_FirstContact;
        public InputAction @FirstPosition => m_Wrapper.m_Touch_FirstPosition;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @FirstContact.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstContact;
                @FirstContact.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstContact;
                @FirstContact.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstContact;
                @FirstPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstPosition;
                @FirstPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstPosition;
                @FirstPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstPosition;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FirstContact.started += instance.OnFirstContact;
                @FirstContact.performed += instance.OnFirstContact;
                @FirstContact.canceled += instance.OnFirstContact;
                @FirstPosition.started += instance.OnFirstPosition;
                @FirstPosition.performed += instance.OnFirstPosition;
                @FirstPosition.canceled += instance.OnFirstPosition;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnFirstContact(InputAction.CallbackContext context);
        void OnFirstPosition(InputAction.CallbackContext context);
    }
}
